spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskpulse
    username: taskpulse
    password: secretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration